spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lease?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    baseline-on-migrate: true
logging:
  level:
   root: info

server:
  port: 9090
